import type { Metadata } from "next";
import "./globals.css";
import { dana, jet } from "@/lib"
import { Locale, i18n } from "@/i18n.config";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return i18n.locales.map(locale => ({ lang: locale }))
}


export default function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: {
    lang: Locale
  }
}>) {
  return (
    <html lang={params.lang}>
      <body>{children}</body>
    </html>
  );
}
